# Generated by Django 5.0.7 on 2024-08-29 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='myapp.project'),
        ),
        migrations.AlterField(
            model_name='commercialization',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercializations', to='myapp.project'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='myapp.project'),
        ),
        migrations.AlterField(
            model_name='newinvention',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_inventions', to='myapp.project'),
        ),
        migrations.AlterField(
            model_name='ongoingproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ongoing_projects', to='myapp.project'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='myapp.project'),
        ),
    ]
